port:  5000
markdown: kramdown
name: Open Gov Hack Night
url: http://opengovhacknight.org
description: "Chicago's place to build, share, and learn about civic tech."
encoding: utf-8
timezone: America/Chicago
navigation:
- text: Home
  url: /index.html
- text: Events
  url: /events/index.html
  category: events
- text: Projects
  url: /projects.html
- text: People
  url: /people.html
- text: Resources
  url: /resources.html
- text: Discussion
  url: /discussion.html